# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e38e209ba69ef7dc7e316b1e575f2d9f0f1a949ebd9ad7d08b907d0363f3a7ee1c65032d605b6383e92043cf9a693aaf181e1b4fce133caa3a5589df3024d61

test:
  secret_key_base: 89f2534e8cdd4a9ec789964fd0396708424f8f72694303cec2574a9ca912cac5e86447e59251430907f897208e7a6d44778895df5f2913c5a282feaa734dfba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
